// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvATGpKjmtazWbk8VBlQXrULAr1elMGBk',
    appId: '1:1027065219417:web:2f41ebf02f6fb5cfdfe448',
    messagingSenderId: '1027065219417',
    projectId: 'staj-bul-demo',
    authDomain: 'staj-bul-demo.firebaseapp.com',
    storageBucket: 'staj-bul-demo.firebasestorage.app',
    measurementId: 'G-Z70Z9W6VPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb_0Kec9RQoWcDgvWjNnyOzW5aEtQXiD0',
    appId: '1:1027065219417:android:74376e8a6cf4f200dfe448',
    messagingSenderId: '1027065219417',
    projectId: 'staj-bul-demo',
    storageBucket: 'staj-bul-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIW5SxTUJFJX2TXB2r_oZgv4Ao590iuak',
    appId: '1:1027065219417:ios:538e36c862cf2236dfe448',
    messagingSenderId: '1027065219417',
    projectId: 'staj-bul-demo',
    storageBucket: 'staj-bul-demo.firebasestorage.app',
    iosBundleId: 'com.example.stajBulDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIW5SxTUJFJX2TXB2r_oZgv4Ao590iuak',
    appId: '1:1027065219417:ios:538e36c862cf2236dfe448',
    messagingSenderId: '1027065219417',
    projectId: 'staj-bul-demo',
    storageBucket: 'staj-bul-demo.firebasestorage.app',
    iosBundleId: 'com.example.stajBulDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvATGpKjmtazWbk8VBlQXrULAr1elMGBk',
    appId: '1:1027065219417:web:71de026d48ce2f0edfe448',
    messagingSenderId: '1027065219417',
    projectId: 'staj-bul-demo',
    authDomain: 'staj-bul-demo.firebaseapp.com',
    storageBucket: 'staj-bul-demo.firebasestorage.app',
    measurementId: 'G-0YS5680GVJ',
  );
}
