class CategoryKeywords {
  static const List<String> software = [
    'software',
    'yazilim',
    'yazılım',
    'developer',
    'gelistirici',
    'geliştirici',
    'code',
    'kod',
    'programming',
    'programlama',
    'frontend',
    'backend',
    'fullstack',
    'mobile',
    'mobil',
    'web',
    'flutter',
    'react',
    'vue',
    'angular',
    'node',
    'django',
    'java',
    'python',
    'c#',
    'cpp',
    'c++',
    'swift',
    'kotlin',
    'javascript',
    'typescript',
    'golang',
    'php'
  ];

  static const List<String> dataScience = [
    'data science',
    'veri bilimi',
    'data analyst',
    'veri analisti',
    'machine learning',
    'makine ogrenmesi',
    'makine öğrenmesi',
    'ai',
    'artificial intelligence',
    'yapay zeka',
    'deep learning',
    'derin ogrenme',
    'derin öğrenme',
    'data engineer',
    'veri mühendisi',
    'veri muhendisi',
    'big data',
    'büyük veri',
    'sql',
    'pandas',
    'numpy',
    'tensorflow',
    'pytorch',
    'veri analizi'
  ];

  static const List<String> design = [
    'design',
    'tasarim',
    'tasarım',
    'ux',
    'ui',
    'product design',
    'grafik',
    'graphic',
    'illustrator',
    'photoshop',
    'figma',
    'adobe',
    '3d',
    'animation',
    'animasyon'
  ];

  static const List<String> marketing = [
    'marketing',
    'pazarlama',
    'seo',
    'sem',
    'social media',
    'sosyal medya',
    'digital marketing',
    'dijital pazarlama',
    'brand',
    'marka',
    'content',
    'icerik',
    'içerik',
    'reklam',
    'ads',
    'growth'
  ];

  static const List<String> engineering = [
    'engineering',
    'muhendislik',
    'mühendislik',
    'mechanical',
    'makine',
    'electrical',
    'elektrik',
    'electronics',
    'elektronik',
    'civil',
    'insaat',
    'inşaat',
    'chemical',
    'kimya',
    'industrial',
    'endustri',
    'endüstri',
    'aerospace',
    'havacilik',
    'havacılık',
    'mechatronics',
    'mekatronik'
  ];
}
